### PR TITLE
feat: enhance export api with log event data

### PR DESCRIPTION
**Pull request by kotharironak**
## Description
Recently, we added support for log events associated with span. This change adds support in export API to download log event attributes associated with span.

### Testing
- added unit test for log event validation
- verified locally running the docker-compose setup

example request:
```
{
  exportSpans(
    limit: 2
    between: {startTime: "2021-05-25T15:56:00.979Z", endTime: "2021-05-25T16:56:00.979Z"}
    filterBy: [{operator: EQUALS, value: "00000000000000004e85a9d8e602e1f4", type: ID, idType: TRACE}]
  ) {
    result
  }
}
```

example response:
```
{
  "data": {
    "exportSpans": {
      "result": "{\"resourceSpans\":[{\"resource\":{\"attributes\":[{\"key\":\"service.name\",\"value\":{\"stringValue\":\"frontend\"}}]},\"instrumentationLibrarySpans\":[{\"spans\":[{\"traceId\":\"00000000000000004e85a9d8e602e1f4\",\"spanId\":\"4e85a9d8e602e1f4\",\"name\":\"HTTP GET /dispatch\",\"kind\":\"SPAN_KIND_SERVER\",\"startTimeUnixNano\":\"1621959960309000000\",\"endTimeUnixNano\":\"1621959961046000000\",\"attributes\":[{\"key\":\"http.status_code\",\"value\":{\"stringValue\":\"200\"}},{\"key\":\"component\",\"value\":{\"stringValue\":\"net/http\"}},{\"key\":\"sampler.type\",\"value\":{\"stringValue\":\"const\"}},{\"key\":\"sampler.param\",\"value\":{\"stringValue\":\"true\"}},{\"key\":\"http.url\",\"value\":{\"stringValue\":\"/dispatch?customer=123&nonse=0.6150459492342204\"}},{\"key\":\"servicename\",\"value\":{\"stringValue\":\"frontend\"}},{\"key\":\"http.method\",\"value\":{\"stringValue\":\"GET\"}}],\"events\":[{\"timeUnixNano\":\"1621959960310958000\",\"attributes\":[{\"key\":\"method\",\"value\":{\"stringValue\":\"GET\"}},{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"HTTP request received\"}},{\"key\":\"url\",\"value\":{\"stringValue\":\"/dispatch?customer=123&nonse=0.6150459492342204\"}}]},{\"timeUnixNano\":\"1621959960311547000\",\"attributes\":[{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"Getting customer\"}},{\"key\":\"customer_id\",\"value\":{\"stringValue\":\"123\"}}]},{\"timeUnixNano\":\"1621959960643918000\",\"attributes\":[{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"Found customer\"}}]},{\"timeUnixNano\":\"1621959960644143000\",\"attributes\":[{\"key\":\"event\",\"value\":{\"stringValue\":\"baggage\"}},{\"key\":\"value\",\"value\":{\"stringValue\":\"Rachel's Floral Designs\"}},{\"key\":\"key\",\"value\":{\"stringValue\":\"customer\"}}]},{\"timeUnixNano\":\"1621959960644183000\",\"attributes\":[{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"location\",\"value\":{\"stringValue\":\"115,277\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"Finding nearest drivers\"}}]},{\"timeUnixNano\":\"1621959960845386000\",\"attributes\":[{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"Found drivers\"}}]},{\"timeUnixNano\":\"1621959960846206000\",\"attributes\":[{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"dropoff\",\"value\":{\"stringValue\":\"115,277\"}},{\"key\":\"pickup\",\"value\":{\"stringValue\":\"46,674\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"Finding route\"}}]},{\"timeUnixNano\":\"1621959960847263000\",\"attributes\":[{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"dropoff\",\"value\":{\"stringValue\":\"115,277\"}},{\"key\":\"pickup\",\"value\":{\"stringValue\":\"534,469\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"Finding route\"}}]},{\"timeUnixNano\":\"1621959960847633000\",\"attributes\":[{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"dropoff\",\"value\":{\"stringValue\":\"115,277\"}},{\"key\":\"pickup\",\"value\":{\"stringValue\":\"375,64\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"Finding route\"}}]},{\"timeUnixNano\":\"1621959960889579000\",\"attributes\":[{\"key\":\"level\",\"value\":{\"stringValue\":\"info\"}},{\"key\":\"dropoff\",\"value\":{\"stringValue\":\"115,277\"}},{\"key\":\"pickup\",\"value\":{\"stringValue\":\"347,839\"}},{\"key\":\"event\",\"value\":{\"stringValue\":\"Finding route\"}}]}],\"status\":{}}]}]},{\"resource\":{\"attributes\":[{\"key\":\"service.name\",\"value\":{\"stringValue\":\"frontend\"}}]},\"instrumentationLibrarySpans\":[{\"spans\":[{\"traceId\":\"00000000000000004e85a9d8e602e1f4\",\"spanId\":\"69f5c9591e8de6d2\",\"parentSpanId\":\"4e85a9d8e602e1f4\",\"name\":\"HTTP GET: /customer\",\"startTimeUnixNano\":\"1621959960311000000\",\"endTimeUnixNano\":\"1621959960643000000\",\"attributes\":[{\"key\":\"servicename\",\"value\":{\"stringValue\":\"frontend\"}}],\"status\":{}}]}]}]}"
    }
  }
}
```

formatted response:
```
{
   "resourceSpans":[
      {
         "resource":{
            "attributes":[
               {
                  "key":"service.name",
                  "value":{
                     "stringValue":"frontend"
                  }
               }
            ]
         },
         "instrumentationLibrarySpans":[
            {
               "spans":[
                  {
                     "traceId":"00000000000000004e85a9d8e602e1f4",
                     "spanId":"4e85a9d8e602e1f4",
                     "name":"HTTP GET /dispatch",
                     "kind":"SPAN_KIND_SERVER",
                     "startTimeUnixNano":"1621959960309000000",
                     "endTimeUnixNano":"1621959961046000000",
                     "attributes":[
                        {
                           "key":"http.status_code",
                           "value":{
                              "stringValue":"200"
                           }
                        },
                        {
                           "key":"component",
                           "value":{
                              "stringValue":"net/http"
                           }
                        },
                        {
                           "key":"sampler.type",
                           "value":{
                              "stringValue":"const"
                           }
                        },
                        {
                           "key":"sampler.param",
                           "value":{
                              "stringValue":"true"
                           }
                        },
                        {
                           "key":"http.url",
                           "value":{
                              "stringValue":"/dispatch?customer=123&nonse=0.6150459492342204"
                           }
                        },
                        {
                           "key":"servicename",
                           "value":{
                              "stringValue":"frontend"
                           }
                        },
                        {
                           "key":"http.method",
                           "value":{
                              "stringValue":"GET"
                           }
                        }
                     ],
                     "events":[
                        {
                           "timeUnixNano":"1621959960310958000",
                           "attributes":[
                              {
                                 "key":"method",
                                 "value":{
                                    "stringValue":"GET"
                                 }
                              },
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"HTTP request received"
                                 }
                              },
                              {
                                 "key":"url",
                                 "value":{
                                    "stringValue":"/dispatch?customer=123&nonse=0.6150459492342204"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960311547000",
                           "attributes":[
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"Getting customer"
                                 }
                              },
                              {
                                 "key":"customer_id",
                                 "value":{
                                    "stringValue":"123"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960643918000",
                           "attributes":[
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"Found customer"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960644143000",
                           "attributes":[
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"baggage"
                                 }
                              },
                              {
                                 "key":"value",
                                 "value":{
                                    "stringValue":"Rachel's Floral Designs"
                                 }
                              },
                              {
                                 "key":"key",
                                 "value":{
                                    "stringValue":"customer"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960644183000",
                           "attributes":[
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"location",
                                 "value":{
                                    "stringValue":"115,277"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"Finding nearest drivers"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960845386000",
                           "attributes":[
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"Found drivers"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960846206000",
                           "attributes":[
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"dropoff",
                                 "value":{
                                    "stringValue":"115,277"
                                 }
                              },
                              {
                                 "key":"pickup",
                                 "value":{
                                    "stringValue":"46,674"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"Finding route"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960847263000",
                           "attributes":[
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"dropoff",
                                 "value":{
                                    "stringValue":"115,277"
                                 }
                              },
                              {
                                 "key":"pickup",
                                 "value":{
                                    "stringValue":"534,469"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"Finding route"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960847633000",
                           "attributes":[
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"dropoff",
                                 "value":{
                                    "stringValue":"115,277"
                                 }
                              },
                              {
                                 "key":"pickup",
                                 "value":{
                                    "stringValue":"375,64"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"Finding route"
                                 }
                              }
                           ]
                        },
                        {
                           "timeUnixNano":"1621959960889579000",
                           "attributes":[
                              {
                                 "key":"level",
                                 "value":{
                                    "stringValue":"info"
                                 }
                              },
                              {
                                 "key":"dropoff",
                                 "value":{
                                    "stringValue":"115,277"
                                 }
                              },
                              {
                                 "key":"pickup",
                                 "value":{
                                    "stringValue":"347,839"
                                 }
                              },
                              {
                                 "key":"event",
                                 "value":{
                                    "stringValue":"Finding route"
                                 }
                              }
                           ]
                        }
                     ],
                     "status":{
                        
                     }
                  }
               ]
            }
         ]
      },
      {
         "resource":{
            "attributes":[
               {
                  "key":"service.name",
                  "value":{
                     "stringValue":"frontend"
                  }
               }
            ]
         },
         "instrumentationLibrarySpans":[
            {
               "spans":[
                  {
                     "traceId":"00000000000000004e85a9d8e602e1f4",
                     "spanId":"69f5c9591e8de6d2",
                     "parentSpanId":"4e85a9d8e602e1f4",
                     "name":"HTTP GET: /customer",
                     "startTimeUnixNano":"1621959960311000000",
                     "endTimeUnixNano":"1621959960643000000",
                     "attributes":[
                        {
                           "key":"servicename",
                           "value":{
                              "stringValue":"frontend"
                           }
                        }
                     ],
                     "status":{
                        
                     }
                  }
               ]
            }
         ]
      }
   ]
}
```

### Checklist:
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by aaron-steinfeld** [comment]
This looks like real data, seems concerning that we see a trace id == span id, no? Are we mixing up fields somewhere, or maybe accidentally fetching an api trace id instead of a regular trace id?

```
        "traceId":"00000000000000004e85a9d8e602e1f4",
        "spanId":"4e85a9d8e602e1f4",
```

**Review by aaron-steinfeld — COMMENTED** [review]
lgtm other than comment about matched ids

**Comment by kotharironak** [comment]
> This looks like real data, seems concerning that we see a trace id == span id, no? Are we mixing up fields somewhere, or maybe accidentally fetching an api trace id instead of a regular trace id?
> 
> ```
>         "traceId":"00000000000000004e85a9d8e602e1f4",
>         "spanId":"4e85a9d8e602e1f4",
> ```

No, that's how the trace is. I have used hotrod application while testing, and the way it has instrumented, it has traceId of the first root span (having no parent span) of an entire trace, so traceId and spanId matches for the root span. As an example, I have captured the below root span using another tool for hotrod application and `full-trace.json.txt` contains full trace.


**The root span of the trace having no parent:**
```
{
   "traceID":"428a446492d20279",
   "spanID":"428a446492d20279",
   "flags":1,
   "operationName":"HTTP GET /dispatch",
   "references":[
      
   ],
   "startTime":1622013186191622,
   "duration":724324,
   "tags":[
      {
         "key":"sampler.type",
         "type":"string",
         "value":"const"
      },
      {
         "key":"sampler.param",
         "type":"bool",
         "value":true
      },
      {
         "key":"span.kind",
         "type":"string",
         "value":"server"
      },
      {
         "key":"http.method",
         "type":"string",
         "value":"GET"
      },
      {
         "key":"http.url",
         "type":"string",
         "value":"/dispatch?customer=123&nonse=0.5858424083504268"
      },
      {
         "key":"component",
         "type":"string",
         "value":"net/http"
      },
      {
         "key":"http.status_code",
         "type":"int64",
         "value":200
      },
      {
         "key":"internal.span.format",
         "type":"string",
         "value":"jaeger"
      }
   ],
   "logs":[
      {
         "timestamp":1622013186191683,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"HTTP request received"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"method",
               "type":"string",
               "value":"GET"
            },
            {
               "key":"url",
               "type":"string",
               "value":"/dispatch?customer=123&nonse=0.5858424083504268"
            }
         ]
      },
      {
         "timestamp":1622013186191743,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Getting customer"
            },
            {
               "key":"customer_id",
               "type":"string",
               "value":"123"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            }
         ]
      },
      {
         "timestamp":1622013186510882,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Found customer"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            }
         ]
      },
      {
         "timestamp":1622013186510983,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"baggage"
            },
            {
               "key":"key",
               "type":"string",
               "value":"customer"
            },
            {
               "key":"value",
               "type":"string",
               "value":"Rachel's Floral Designs"
            }
         ]
      },
      {
         "timestamp":1622013186510987,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding nearest drivers"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"location",
               "type":"string",
               "value":"115,277"
            }
         ]
      },
      {
         "timestamp":1622013186721599,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Found drivers"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            }
         ]
      },
      {
         "timestamp":1622013186721991,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"374,801"
            }
         ]
      },
      {
         "timestamp":1622013186722033,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"794,289"
            }
         ]
      },
      {
         "timestamp":1622013186722219,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"650,236"
            }
         ]
      },
      {
         "timestamp":1622013186773825,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"306,409"
            }
         ]
      },
      {
         "timestamp":1622013186776742,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"113,8"
            }
         ]
      },
      {
         "timestamp":1622013186777937,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"838,84"
            }
         ]
      },
      {
         "timestamp":1622013186820516,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"880,210"
            }
         ]
      },
      {
         "timestamp":1622013186827460,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"161,458"
            }
         ]
      },
      {
         "timestamp":1622013186839628,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"446,514"
            }
         ]
      },
      {
         "timestamp":1622013186866696,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Finding route"
            },
            {
               "key":"dropoff",
               "type":"string",
               "value":"115,277"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            },
            {
               "key":"pickup",
               "type":"string",
               "value":"369,759"
            }
         ]
      },
      {
         "timestamp":1622013186915853,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Found routes"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            }
         ]
      },
      {
         "timestamp":1622013186915921,
         "fields":[
            {
               "key":"event",
               "type":"string",
               "value":"Dispatch successful"
            },
            {
               "key":"driver",
               "type":"string",
               "value":"T722509C"
            },
            {
               "key":"eta",
               "type":"string",
               "value":"2m0s"
            },
            {
               "key":"level",
               "type":"string",
               "value":"info"
            }
         ]
      }
   ]
}
```

**Entire trace:**
- Attached as full-trace.json
[full-trace.json.txt](https://github.com/hypertrace/hypertrace-core-graphql/files/6544723/full-trace.json.txt)

**Comment by aaron-steinfeld** [comment]
Got it, thanks for following up. Still strange to me that whichever instrumentation would use the same guid for both, but that's irrelevant to this PR.

**Review by aaron-steinfeld — APPROVED** [review]

**Pull request merged**
